@startuml
'https://plantuml.com/class-diagram

class HandlerExecutionChain {
     - Object : handler
     - List<HandlerInterceptor> : interceptorList

     + void applyPreHandle()
     + void applyPostHandle()
     + void triggerAfterCompletion()
     + void applyAfterConcurrentHandlingStarted()

}


interface HandlerInterceptor
note right of HandlerInterceptor : 方法拦截器

HandlerExecutionChain "1" *-- "Many" HandlerInterceptor

@enduml