@startuml
'https://plantuml.com/class-diagram

interface Filter {
    default void init(FilterConfig filterConfig)
    doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
    default void destroy()

}
interface FilterConfig
interface ApplicationFilterConfig

interface FilterChain
interface ApplicationFilterChain

FilterConfig <|-- ApplicationFilterConfig
Filter --* ApplicationFilterConfig

FilterChain <|-- ApplicationFilterChain
ApplicationFilterConfig --* ApplicationFilterChain

interface Filter

@enduml
