@startuml
'https://plantuml.com/class-diagram

interface FlyBehavior {
    fly()
}

interface QuackBehavior {

    quack()
}

class MuteQuack {
}

class Quack {
}

class Squeak {
}

class FlyNoWay {
}

class FlyWithWings {
}

abstract class Duck {
}

FlyNoWay .up.|> FlyBehavior
FlyWithWings .up.|> FlyBehavior

MuteQuack .up.|> QuackBehavior
Quack .up.|> QuackBehavior
Squeak .up.|> QuackBehavior

Duck -up-> FlyBehavior
Duck -up-> QuackBehavior






@enduml
