spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: pw-Aa123456
      database: 0
      timeout: 10000

logging:
  level:
    root: INFO
    com.iokays.sample: DEBUG

  # 控制台输出配置
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %green(%m) %n"
