spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: pw-guest
    virtual-host: /



logging:
  level:
    root: INFO
    com.iokays.sample: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG

  # 控制台输出配置
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %green(%m) %n"
