@startuml
'https://plantuml.com/class-diagram

interface Observer {
update()
}

interface Subject {
    registerObserver()
    removeObserver()
    notifyObservers()
}

class ConcreteObserver {
    update()
}

class ConcreteSubject {
    registerObserver()
    removeObserver()
    notifyObservers()
}

Subject -right-> Observer

ConcreteObserver .up.|> Observer
ConcreteSubject .up.|> Subject

ConcreteObserver -left-> ConcreteSubject

@enduml