spring:
  application:
    name: spring-value-sample
  properties:
    array: 1,2,3,5
    map: "{key1: 'value1', key2: 'value2'}"

logging:
  level:
    root: INFO
    com.iokays.sample: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG

  # 控制台输出配置
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %green(%m) %n"
