spring:
  profiles:
    include: encrypted
  application:
    name: work
  datasource:
    driverClassName: com.clickhouse.jdbc.ClickHouseDriver
    url: ENC(vNtrLEP5nH6Pf5Oi1quoCxQ/H5VMYTeDyf1QVcPnFw8aCzg+FdvaeOzX9xwYFy6dP1wOuBMBiXfRTKOX5ArxNbiAucmTmoFTI+4baQKcOLk1DHGYRrBrz8o3zxOLtYZxW9wzQinPncI=)
    userName: ENC(q87XXp++shvMQyETKzGMtA==)
    password: ENC(9Hc8dg6YVgMaOvkr2cOAr8V8lWQXv+xl)
  elasticsearch:
    uris: [http://localhost:9200]
    socket-keep-alive: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss