@startuml
'https://plantuml.com/class-diagram

interface Duck {
    + quack()
    + fly()
}

class MallardDuck {
    + quack()
    + fly()
}

interface Turkey {
    + gobble()
    + fly()
}

class WildTurkey {
    + gobble()
    + fly()
}

class TurkeyAdapter {
    - turkey: Turkey
    + quack()
    + fly()
}

MallardDuck .up.|> Duck
TurkeyAdapter .up.|> Duck

WildTurkey .up.|> Turkey
TurkeyAdapter -left-> Turkey

@enduml