@startuml
'https://plantuml.com/object-diagram

interface Filter

interface Aware

interface BeanNameAware
interface EnvironmentAware
interface ServletContextAware

note left of Filter: Servlet的过滤器

abstract class GenericFilterBean {
init()
}

note left of GenericFilterBean
需理解 aware
end note

abstract class OncePerRequestFilter {
doFilterInternal()
}

class WebAsyncManagerIntegrationFilter {
}

note left of WebAsyncManagerIntegrationFilter
final class
end note


Aware <|-- BeanNameAware
Aware <|-- EnvironmentAware
Aware <|-- ServletContextAware

Filter <|-- GenericFilterBean
BeanNameAware <|-- GenericFilterBean
EnvironmentAware <|-- GenericFilterBean
ServletContextAware <|-- GenericFilterBean

GenericFilterBean <|-- OncePerRequestFilter

OncePerRequestFilter <|-- WebAsyncManagerIntegrationFilter

@enduml
