@startuml
'https://plantuml.com/class-diagram

abstract class ApplicationEvent #palegreen

interface ApplicationListener #palegreen

interface ApplicationEventPublisher #palegreen

abstract class AbstractApplicationContext

interface ApplicationContext

interface ConfigurableApplicationContext


ApplicationEventPublisher .up.> ApplicationEvent

AbstractApplicationContext .up.|> ApplicationEventPublisher





'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

@enduml