spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: sa
    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
